---
title: "Rmarkdown Day 2"
author: "Nyssa"
date: "3/2/2021"
output: 
 html_document:
    toc: TRUE
    toc_float: TRUE

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.path="../output/")
```

# Introduction

Today, we will use palmer penguins to manipulate figures in RMarkdown

# Load libraries

```{r}
library(palmerpenguins)
library(tidyverse)
library(kableExtra)
```

# Make a plot  

```{r PenguinFig, fig.align="center", fig.cap="This is a boxplot of penguins"}
PenguinFigure<-penguins %>%
  ggplot(aes(x = species, y = flipper_length_mm, color = island))+
  geom_boxplot()

PenguinFigure
```

# Make a table

We are looking at bill length of  **Gentoo** penguins from Biscoe.

```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% # make it a kable table
  #kable_classic()
  kable_paper() %>%
  row_spec(2, bold = T, color = "white", background = "red")
```



